update to latest rust, drop msrv since older versions fail to build spade
  cargo check --all-targets --no-default-features

Build error is:

https://github.com/georust/geo/actions/runs/10101238242/job/27934367105?pr=1197

error[E0446]: crate-private type `PointWithIndex<V>` in public interface
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/spade-2.10.0/src/delaunay_core/bulk_load.rs:357:1
    |
342 |   pub(crate) struct PointWithIndex<V> {
    |   ----------------------------------- `PointWithIndex<V>` declared as crate-private
...
357 | / pub fn bulk_load_stable<V, T, T2, Constructor>(
358 | |     constructor: Constructor,
359 | |     elements: Vec<V>,
360 | | ) -> Result<T, InsertionError>
...   |
370 | |     >,
371 | |     Constructor: FnOnce(Vec<PointWithIndex<V>>) -> Result<T2, InsertionError>,
    | |______________________________________________________________________________^ can't leak crate-private type